BE/src/main/java/com/FTIsland/BE/domain/Role.java
- [fix] Role에서 GUEST를 ADMIN으로 수정
- [config] GCP 300$ 무료 크레딧을 위해 계정을 새로 생성함
=> [config] GCP 300$ 무료 크레딧을 위한 계정 변경

BE/src/main/java/com/FTIsland/BE/config/SecurityConfig.java, BE/src/main/java/com/FTIsland/BE/jwt/service/JwtService.java, BE/src/main/java/com/FTIsland/BE/oauth2/handler/OAuth2LoginSuccessHandler.java
- bearer로 accessToken을 전달
- /oauth2/sign-up으로 리다이렉트, 현재 화면이 없어서 404
=> [fix] 구글 OAuth2 로그인 후 success handler redirect

BE/src/main/java/com/FTIsland/BE/config/SecurityConfig.java, BE/src/main/java/com/FTIsland/BE/controller/ReadController.java, BE/src/main/java/com/FTIsland/BE/dto/ReadDTO.java, BE/src/main/java/com/FTIsland/BE/entity/ReadEntity.java, BE/src/main/java/com/FTIsland/BE/repository/ReadRepository.java, BE/src/main/java/com/FTIsland/BE/service/ReadService.java
- offset과 limitNum 정보를 받아서 저장 및 업데이트
- 마지막으로 읽은 페이지를 반환
- 예약어 문제 때문에 limit 대신 limitNum으로 변경됨.
=> [feat] 마지막으로 읽은 페이지 API 구현

BE/build.gradle, BE/src/main/java/com/FTIsland/BE/service/BookContentService.java
- build.gradle에 cloud storage 관련 의존성 추가
- BookContentService의 imageURL에 cloud에 있는 이미지 URL 설정
- 추후 Book 관련 정보 추가 시 image를 받아 cloud에 저장해야 함
=> [fix] Google cloud storage bucket에 이미지 저장 및 BookContentDTO 저장 확인

BE/src/main/java/com/FTIsland/BE/config/SecurityConfig.java, BE/src/main/java/com/FTIsland/BE/controller/RecentBookController.java, BE/src/main/java/com/FTIsland/BE/dto/RecentBookDTO.java, BE/src/main/java/com/FTIsland/BE/repository/ReadRepository.java, BE/src/main/java/com/FTIsland/BE/service/RecentBookService.java
- userId 받으면 최근에 읽은 동화들을 동화 정보 DTO list로 response
- 동화들은 readEntity의 updatedAt 정보를 기준으로 정렬
- updatedAt 정보도 전달
- 나중에 updatedAt이 LocalDateTime 형식이라서 제대로 response를 받을 수 없다면 String으로 변환 후 보내는 것으로 수정하겠습니다!
=> [feat] 최근에 탐험한 이야기 API 구현

BE/src/main/java/com/FTIsland/BE/dto/BookContentDTO.java, BE/src/main/java/com/FTIsland/BE/service/BookContentService.java
- DTO에 주언어 보조언어도 같이 담아서 보내는 것으로 수정했습니다!
=> [fix] tts api 사용 시 필요한 mainLan, subLan 정보 DTO에 추가

BE/src/main/java/com/FTIsland/BE/config/SecurityConfig.java, BE/src/main/java/com/FTIsland/BE/controller/ExploreController.java, BE/src/main/java/com/FTIsland/BE/dto/ExploreDTO.java, BE/src/main/java/com/FTIsland/BE/service/ExploreService.java
- userId랑 bookId를 받아서 read여부, offset, limit을 보내는 API 구현
- 읽었을 경우 read true -> 마저 읽기 / 처음부터 읽기
- 안읽었을경우 read false -> 처음부터 읽기
- read true & 마저 읽기 -> offset/limit 으로 읽던 부분 부터 보여주기
- read false -> (default offset 0, default limit 1) 무조건 처음부터 읽기
=> [feat] 동화 읽으러가기 API 구현

BE/build.gradle, BE/src/main/java/com/FTIsland/BE/config/WebConfig.java
- 배포 후 cors 문제 해결을 위한 web config 추가
- spring security도 dependency 삭제
=> [fix] 배포 후 cors 문제 해결을 위한 web config 추가

BE/src/main/java/com/FTIsland/BE/controller/IslandInfoController.java, BE/src/main/java/com/FTIsland/BE/dto/BookInfoDTO.java, BE/src/main/java/com/FTIsland/BE/dto/ExploreDTO.java, BE/src/main/java/com/FTIsland/BE/dto/IslandBooksDTO.java, BE/src/main/java/com/FTIsland/BE/dto/IslandInfoDTO.java, BE/src/main/java/com/FTIsland/BE/dto/ReadDTO.java, BE/src/main/java/com/FTIsland/BE/dto/RecentBookDTO.java, BE/src/main/java/com/FTIsland/BE/entity/BookInfoEntity.java, BE/src/main/java/com/FTIsland/BE/entity/IslandInfoEntity.java, BE/src/main/java/com/FTIsland/BE/entity/ReadEntity.java, BE/src/main/java/com/FTIsland/BE/repository/BookInfoRepository.java, BE/src/main/java/com/FTIsland/BE/repository/IslandInfoRepository.java, BE/src/main/java/com/FTIsland/BE/repository/ReadRepository.java, BE/src/main/java/com/FTIsland/BE/service/BookInfoService.java, BE/src/main/java/com/FTIsland/BE/service/ExploreService.java, BE/src/main/java/com/FTIsland/BE/service/IslandInfoService.java, BE/src/main/java/com/FTIsland/BE/service/ReadService.java
- 회원인 경우 읽은 정보 검색해서 진행도와 함께 반환
- 비회원인 경우 검색하지 않고 book info만 반환
=> [feat] 섬 정보 API 구현 완료

BE/src/main/java/com/FTIsland/BE/controller/LoginController.java, BE/src/main/java/com/FTIsland/BE/dto/ResponseDTO.java, BE/src/main/java/com/FTIsland/BE/dto/ResponseUtil.java, BE/src/main/java/com/FTIsland/BE/entity/ResponseStatus.java, BE/src/main/java/com/FTIsland/BE/service/BookInfoService.java, BE/src/main/java/com/FTIsland/BE/service/LoginService.java
- response status를 http servlet response로 수정
- 임시 데이터는 추후 추가 예정, issue를 그대로 둠
=> [feat] 임시 데이터 생성 준비

BE/src/main/java/com/FTIsland/BE/dto/VocaDTO.java, BE/src/main/java/com/FTIsland/BE/entity/UserVocaEntity.java, BE/src/main/java/com/FTIsland/BE/entity/VocaEntity.java, BE/src/main/java/com/FTIsland/BE/repository/UserVocaRepository.java, BE/src/main/java/com/FTIsland/BE/repository/VocaRepository.java
- voca관련 DTO, Entity, Repository 
- userId가 Long -> Integer로 바뀌면서 전체 다 적용해야하는데 아직 일부분만 바뀌어있어서 제가 나머지 안된 부분 바꾸기 위해서 우선 하던거 merge합니다
=> [feat] voca API 사전작업

BE/src/main/java/com/FTIsland/BE/dto/QuizDTO.java, BE/src/main/java/com/FTIsland/BE/dto/UserInfoDTO.java, BE/src/main/java/com/FTIsland/BE/dto/UserLanguageDTO.java, BE/src/main/java/com/FTIsland/BE/entity/User.java, BE/src/main/java/com/FTIsland/BE/repository/ReadRepository.java, BE/src/main/java/com/FTIsland/BE/repository/UserRepository.java, BE/src/main/java/com/FTIsland/BE/service/UserService.java
- 여기저기 안바뀌어있던 userId type 통일 시켰습니다.
=> [fix] userId type 변환 관련 문제 해결

BE/src/main/java/com/FTIsland/BE/BeApplication.java, BE/src/main/java/com/FTIsland/BE/controller/VocaController.java, BE/src/main/java/com/FTIsland/BE/service/VocaService.java, BE/src/main/resources/application.yml
- userId와 vocaId를 요청 받으면 UserVoca 테이블에 추가 후 201 created STATUS와 함께 id를 uri로 반환하는 API 구현
- 만약 response body로 id를 받고 싶다면 slack으로 말씀해주시면 수정해서 반영해두겠습니다.
=> [feat] 단어 추가 API 구현

BE/src/main/java/com/FTIsland/BE/controller/VocaController.java, BE/src/main/java/com/FTIsland/BE/dto/VocaDescriptionDTO.java, BE/src/main/java/com/FTIsland/BE/entity/VocaEntity.java, BE/src/main/java/com/FTIsland/BE/service/VocaService.java
- parameter로 vocaId, mainLan, subLan을 받으면 word, description, bookName의 list 넘기는 API
list의 index 0은 주 언어, index 1은 보조 언어
=> [feat] 단어 설명 API 구현

BE/src/main/java/com/FTIsland/BE/controller/IslandInfoController.java
- 소수점 아래 둘째자리까지 출력하도록 수정
- 만약 readEntityOptional이 있는 경우에만 read table 검색하도록 수정
=> [fix] /island/books에서 progress 값 반환 수정

BE/src/main/java/com/FTIsland/BE/controller/VocaController.java, BE/src/main/java/com/FTIsland/BE/repository/UserVocaRepository.java, BE/src/main/java/com/FTIsland/BE/service/VocaService.java
- userId를 요청하면 해당 사용자의 단어장에 있는 단어들 조회 후 번역하여 리스트 반환
=> [feat] 단어장 API 구현

BE/src/main/java/com/FTIsland/BE/controller/LanguageController.java, BE/src/main/java/com/FTIsland/BE/service/UserService.java
- update를 고려하여 POST -> PUT으로 수정
=> [fix] 주언어, 보조언어 업데이트 API 수정 

BE/src/main/java/com/FTIsland/BE/controller/VocaController.java, BE/src/main/java/com/FTIsland/BE/entity/VocaEntity.java, BE/src/main/java/com/FTIsland/BE/service/BookContentService.java, BE/src/main/java/com/FTIsland/BE/service/VocaService.java
- book content 단어 수정
- voca 데이터 생성을 위한 voca controller, voca service 추가
=> [feat] STATIC 동화-단어 추가 구현

BE/src/main/java/com/FTIsland/BE/controller/BookFeedbackController.java, BE/src/main/java/com/FTIsland/BE/dto/BookFeedbackDTO.java, BE/src/main/java/com/FTIsland/BE/service/BookFeedbackService.java
- 생각해보기 문제에 대한 쉬움/보통/어려움 feedback을 입력받음
- 입력받은 정보를 바탕으로 user의 level 업데이트
- level의 min = 3, max = 9
=> [feat] 난이도 설문 API 구현 완료

BE/src/main/java/com/FTIsland/BE/dto/BookContentDTO.java, BE/src/main/java/com/FTIsland/BE/dto/ContentVocaDTO.java, BE/src/main/java/com/FTIsland/BE/repository/VocaRepository.java, BE/src/main/java/com/FTIsland/BE/service/BookContentService.java, BE/src/main/java/com/FTIsland/BE/service/VocaService.java
- 해당 동화의 page 별로 단어 조회
- 그 후 각각을 DTO에 담아서 반환하도록 변경
=> [fix] 동화 내용 API에 단어 list 추가

BE/src/main/java/com/FTIsland/BE/service/VocaService.java
- VocaService Optional 관련 isPresent 추가
=> [fix] VocaService Optional 관련 isPresent 추가

BE/src/main/java/com/FTIsland/BE/repository/UserVocaRepository.java, BE/src/main/java/com/FTIsland/BE/service/VocaService.java
=> [fix] 단어 추가 api 중복 처리

BE/src/main/java/com/FTIsland/BE/controller/QuizController.java, BE/src/main/java/com/FTIsland/BE/service/BookInfoService.java, BE/src/main/java/com/FTIsland/BE/service/ChatGptService.java
- 반말로만 질문하도록 하여 반말/존댓말 섞여서 나오던 버그 수정
- description까지 추가로 제공하여 질문의 퀄리티를 높히는 작업
=> [fix] 생각해보기 질문 API 수정

BE/src/main/java/com/FTIsland/BE/controller/IslandInfoController.java
- island id - book id 저장이 되어 있는 경우에 잘 리턴하도록 수정
- 비회원인 경우 -> progress가 0.00인 island - book 반환
- 회원이고 현재 island에서 읽은 책이 있는 경우 -> progress가 반영된 island - book 반환
- 회원이고 현재 island에서 읽은 책이 없는 경우 -> progress가 0.00으로 반영된 island - book 반환
=> [fix] 섬 정보 API 회원일 경우 반환 형식 수정

BE/src/main/java/com/FTIsland/BE/controller/QuizController.java, BE/src/main/java/com/FTIsland/BE/entity/QuizEntity.java, BE/src/main/java/com/FTIsland/BE/repository/QuizRepository.java, BE/src/main/java/com/FTIsland/BE/service/ChatGptService.java, BE/src/main/java/com/FTIsland/BE/service/QuizService.java, BE/src/main/java/com/FTIsland/BE/service/TranslationService.java
- 동화 content를 사용하여 생각해보기 퀴즈 생성 기능의 성능을 향상
- 사용자 맞춤형으로 그때 그때 생성하는 방식에서 수정함.
- 동화-level 조합으로 저장된 퀴즈가 있다면 번역 후 반환
- 없다면 생성하고 저장하고 번역 후 반환 
- 퀴즈 생성 기능 개선을 통한 퀄리티 향상 (추후에 DTO 정리 예정)
=> [fix] 생각해보기 퀴즈 생성 성능(질문 퀄리티 + 응답 속도) 향상

BE/src/main/java/com/FTIsland/BE/controller/VocaController.java, BE/src/main/java/com/FTIsland/BE/dto/BookVocaDescriptionDTO.java, BE/src/main/java/com/FTIsland/BE/service/VocaService.java
- /book/voca/description 에 get 방식으로 vocaId와 언어를 파라미터로 받기
- 단어 설명 번역 후 이미지와 같이 반환
=> [feat] 단어 설명 API (동화에서 볼 때)

BE/src/main/java/com/FTIsland/BE/controller/VocaController.java, BE/src/main/java/com/FTIsland/BE/dto/VocaStarDTO.java, BE/src/main/java/com/FTIsland/BE/service/VocaService.java
- userId와 vocaId를 요청 받으면 요청값과 함께 isStar 정보를 반환
- isStar이 true면 해당 회원이 그 단어를 단어장에 이미 즐겨찾기를 했다는 것
=> [feat] 단어 즐겨찾기 여부 확인 API

BE/.gitignore, BE/src/main/resources/application-API-KEY.yml, BE/src/main/resources/application-chatgpt.yml, BE/src/main/resources/application-oauth.yml, BE/src/main/resources/application.yml
- README 실행방법대로 하기 위한 .gitignore 수정
=> [docs] README 실행방법대로 하기 위한 .gitignore 수정

BE/src/main/java/com/FTIsland/BE/dto/ExploreDTO.java, BE/src/main/java/com/FTIsland/BE/dto/ReadDTO.java, BE/src/main/java/com/FTIsland/BE/entity/ReadEntity.java, BE/src/main/java/com/FTIsland/BE/service/ExploreService.java, BE/src/main/java/com/FTIsland/BE/service/ReadService.java, BE/src/main/resources/application.yml
- docker로 띄운 MariaDB와 프로젝트 연결 
- Spring boot 프로젝트 실행 후 테이블 생성 확인
=> [fix] docker MariaDB 데이터베이스 연결
